
export default {
  "login": "Sway2003",
  "id": 105355748,
  "node_id": "U_kgDOBkeZ5A",
  "avatar_url": "https://avatars.githubusercontent.com/u/105355748?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Sway2003",
  "html_url": "https://github.com/Sway2003",
  "followers_url": "https://api.github.com/users/Sway2003/followers",
  "following_url": "https://api.github.com/users/Sway2003/following{/other_user}",
  "gists_url": "https://api.github.com/users/Sway2003/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Sway2003/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Sway2003/subscriptions",
  "organizations_url": "https://api.github.com/users/Sway2003/orgs",
  "repos_url": "https://api.github.com/users/Sway2003/repos",
  "events_url": "https://api.github.com/users/Sway2003/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Sway2003/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Swayams Bisoyi",
  "company": "Intern ",
  "blog": "",
  "location": "Bhubaneswar,India",
  "email": null,
  "hireable": null,
  "bio": "MERN || UI/UX || Reasoning ",
  "twitter_username": "IamNefarious999",
  "public_repos": 28,
  "public_gists": 0,
  "followers": 6,
  "following": 14,
  "created_at": "2022-05-11T10:05:15Z",
  "updated_at": "2023-08-07T11:10:37Z"
}